### ISSUE TITLE
[IME辞書] Gboard用IME辞書ダウンロード機能の復活

### ISSUE THREAD

**Issue by Guest126** [miyacorata/Lemonade#130]
[Android用「Google日本語入力」がサポート終了](https://pc.watch.impress.co.jp/docs/news/1315547.html)となっていることから、後継となるGboard用のIME辞書ダウンロード機能の復活はできないでしょうか。

> そうそう、アサルトリリィ非公式IME辞書生成機能には既知の問題があり、Android端末でAndroid向けの辞書を落とそうとするとネットワーク接続待機でDLが進まない問題があります
> （最近のAndroidであれば回避策があります）

からはじまる[一連のツイート](https://twitter.com/miyacorata/status/1383846506214563848)を拝見し、過去に一度そうした機能が実装されたものの、今はコメントアウトされたことまでは把握したのですが、再実装のために何かお手伝いできないかと考えています。

PHPのコード(app/Http/Controllers/InfoController.php)を見ても特段おかしいところはなく、AndroidのChromeブラウザから https://lemonade.lily.garden/imedic?format=zip に直接アクセスして問題なくダウンロードできているので、逆にどういった環境で問題が発生するのかが気になっています。

**Comment by miyacorata** [comment]
はじめまして、いつもLemonadeのご利用ありがとうございます！

主題の件ですが、現時点でテストを試みましたがなんの問題もなくDLと辞書インポートができてしまいましたので次回のリリースで復活させます。おまたせして申し訳ありませんが今しばらくお待ち下さい。

**Comment by miyacorata** [comment]
おまたせしました、当該リンクは 58aa5ab で復活し Ver8.0.0 でデプロイされました。

**Comment by Guest126** [comment]
一通りの動作や付加情報に問題ないことを確認しました。対応ありがとうございました。
