### ISSUE TITLE
[IME辞書] MS-IME用システム辞書ダウンロード機能

### ISSUE THREAD

**Issue by Guest126** [miyacorata/Lemonade#131]
MS-IME用のシステム辞書（アドオン辞書、追加辞書、オープン拡張辞書とも呼ばれる）のダウンロード機能を追加できないでしょうか。

システム辞書は、現在Lemonadeで提供されているユーザー辞書(Shift-JIS版)と比べ、

- ダブルクリックで簡単にインストールできる
- オン/オフの切り替え、削除、更新が容易
- ユーザー辞書を大量の単語で汚さない

といったメリットがあります。ユーザー辞書は編集可能ですが、システム辞書は編集不可という違いがあります。

ファイルフォーマットは[Microsoft Office IME 2010 オープン拡張辞書作成用 Excel テンプレート](https://www.microsoft.com/ja-jp/download/details.aspx?id=13030)に付属のXPSドキュメントに記載されています。同様の解説は[IME2010の辞書作成 | きほんのき](http://kihon-no-ki.com/create-ime2010-dictionary)でも読むことができます。

拡張子は.dctxと.dctxcがあり、前者はXMLファイル、後者はそれをCAB圧縮したものになります。どちらであってもシステム辞書として有効です。.dctxの方はPropertyList版の処理を少し変えるだけで実装できそうですが、.dctxcの方はPHPにCAB圧縮の標準関数がないため、やや面倒そうです。

[assaultlily-dic.zip](https://github.com/miyacorata/Lemonade/files/7194491/assaultlily-dic.zip)

試しに現在のユーザー辞書を元に作成したシステム辞書をZIPで添付します。

**Comment by miyacorata** [comment]
オープン拡張辞書(とここでは呼ぶことにします)版、おっしゃるとおり比較的すぐに実装できそうでしたので早急に手を付けます。今週中にはご用意できると思いますのでお待ちくださいませ！

Issueお寄せいただきありがとうございます！

**Comment by miyacorata** [comment]
オープン拡張辞書生成機能については f608b9e で実装され、Ver8.0.0 でデプロイされました。お待たせいたしました、お役に立てば幸いです。

**Comment by Guest126** [comment]
一通りの動作や付加情報に問題ないことを確認しました。対応ありがとうございました。
