### ISSUE TITLE
"・"を名前に含むリリィのIME辞書での扱いについて

### ISSUE THREAD

**Issue by fvh-P** [miyacorata/Lemonade#145]
## 課題

現状、フルネームを変換で出したい場合
- フルネームの読み仮名を入力するしか方法がない
- ルドビコ女学院のリリィなど、"・"を名前に含むリリィでは"・"も入力しないと変換候補に出ない

### 例
「岸本・マリア・未来」を変換で出したい場合
✕ きしもとまりあみらい
○ きしもと・まりあ・みらい

## 提案
1. "・"なしで変換できるようにする
2. 苗字を入力するとフルネームが候補に出るようにする
3. 名前を入力するとフルネームが候補に出るようにする

どれを採用するかは要検討、複数採用してもいいと思います。

追記
Microsoft IME と MacOS 経由で iOS の標準IMEで使ってますが、両方とも同じ挙動をしています。別のIMEだともしかしたら違うのかも…？

**Comment by miyacorata** [comment]
1. については a5e8805dfe447fe7c62d803d63242c5a619020fb で対応しました。次回リリースで反映されます。

**Comment by fvh-P** [comment]
ありがとうございます！

品詞については確かに短縮読みが妥当かなと思います。
