### ISSUE TITLE
【提案】faviconの設置

### ISSUE THREAD

**Issue by kaede3pic** [miyacorata/Lemonade#156]
サイトにファビコンが設置されていないため，ブラウザが繰り返しリクエストを送ってページの読み込み完了までに時間がかかります。
ファビコンの設置を提案します。

**Comment by miyacorata** [comment]
Faviconはすでに設置されているはずでしたが、こちらの不備でFaviconがアップデートごとに空のファイルに上書きされてしまう状態になっておりました。 PR #157 で解消し次回リリース以降反映されます。Issueお寄せいただきありがとうございました。

また念の為補足させていただきますが、Lemonadeの表示速度は主にassaultlily-rdfエンドポイントとの通信待ち及びフォントファイルのロードに起因するものです。私の手元の環境での結果ではありますが、ChromeでのFaviconに関する通信はページ全体の表示が終わったあとに非同期的に行われており、**現在のアクセス規模で**Faviconを設置することによる**見た目上の**表示速度の向上は得られないと思われますので、何卒ご承知おきいただければと思います。とはいえ、Faviconを設置しキャッシュさせることでエラーとなるリクエストが減ると、サーバの負荷軽減にはなりますので、決して無意味ではないと考えます。

**Comment by miyacorata** [comment]
まだリリースはしていませんが、暫定的にFaviconを配置しました。次回リリースで正式対応という形になります。
