### ISSUE TITLE
OGP画像にアイコンを載せる

### ISSUE THREAD

**Issue by Guest126** [miyacorata/Lemonade#187]
OGP画像が味気ないので右側の空きスペースにアイコンを載せる提案です。

[OGPController.php](https://github.com/miyacorata/Lemonade/blob/main/app/Http/Controllers/OGPController.php) 内で

1. アイコン画像を`make`で読み込む
2. アイコン画像をアス比保持で[Resize](http://image.intervention.io/api/resize)
3. アイコン画像をキャンバスに[Insert](http://image.intervention.io/api/insert)

とするだけなら難しくなさそうだと思ったのですが、フルネームが長いリリィだと名前テキストがアイコンに被ってしまうことに気付きました。テキストの折り返しか、全体的なテキスト位置の見直しが必要になってしまいます。

![image](https://user-images.githubusercontent.com/63546117/147486196-b50ff388-146a-4af5-99fd-29a0960d08c7.png)
https://lemonade.lily.garden/ogp/lily/%E3%83%9F%E3%83%AA%E3%82%A2%E3%83%A0%E3%83%BB%E3%83%92%E3%83%AB%E3%83%87%E3%82%AC%E3%83%AB%E3%83%89%E3%83%BBv%E3%83%BB%E3%82%B0%E3%83%AD%E3%83%94%E3%82%A6%E3%82%B9.jpg

見たところ名刺をモチーフにしたOGP画像のようなので、アイコンでなくとも、ルーン文字や校章でも構わないと思います。その場合は文字が被っても問題なさそうです。

身も蓋もないことを言えば、1200x630の巨大カード画像でなくとも、アイコン画像やメモリア画像が存在するものについてはそれをそのままOGP画像として採用すればいいのではという気がしなくもないです。

複数のアイコンのいずれかをランダムで載せる場合、SNSや画像検索でどのように表示されるのか（一定時間キャッシュされるのか、特定のアイコンで永久に固定されるのか、検索結果に複数並ぶのか、いずれかひとつが並ぶのか）は確認しておいた方がいいかもしれません。

**Comment by miyacorata** [comment]
OGPは一度投稿されると投稿されたサービスごとに異なりますがそこそこの期間キャッシュされます。ご指摘の通りアイコン画像等を乗せることは技術的には可能ですが、一人のリリィに複数のアイコンが登録でき、かつランダム表示されるよう設計・実装していることもあり、OGPへのアイコン掲載は意図的にオミットされています。

実のところ、LemonadeのOGPはTwitter等にリンクを掲載したときにURLのみではリンク先の詳細がわからず押しづらい、また(ツイートを見た他のユーザから)押されづらいことの対策として実装された側面が強く、あまり力を入れていなかったりします。しかし、校章やルーン等、各リリィに最大一つで紐付けられる画像データが存在する場合は掲載したいと思っているところではあります。

OGP画像がそこそこ寂しいのは事実なので、なにかLemonadeのロゴ等全リリィが共通で使える画像の用意等も検討したいと思います。
