### ISSUE TITLE
メタ情報がマディックや教導官を考慮していない

### ISSUE THREAD

**Issue by Guest126** [miyacorata/Lemonade#188]
HTMLのメタ情報でマディックや教導官が一律でリリィ扱いになっています。

view-source:https://lemonade.lily.garden/lily/Michikawa_Miaki
```
    <meta name="description" content="リリィ「道川深顯」のプロフィールを閲覧できます。シエルリント女学薗のリリィです。">
    <meta property="og:title" content="道川深顯 - Lemonade">
    <meta property="og:description" content="リリィ「道川深顯」のプロフィールを閲覧できます。シエルリント女学薗のリリィです。">
```
道川深顯の場合、以下のようにマディックとする必要があります。
```
    <meta name="description" content="アサルトリリィの登場人物「道川深顯」のプロフィールを閲覧できます。シエルリント女学薗のマディックです。">
    <meta property="og:title" content="道川深顯 - Lemonade">
    <meta property="og:description" content="アサルトリリィの登場人物「道川深顯」のプロフィールを閲覧できます。シエルリント女学薗のマディックです。">
```
文章はあくまで一例です。

その他のエッジケースとして https://github.com/fvh-P/assaultlily-rdf/blob/master/RDFs/character.ttl に記載のある「[御前](https://lemonade.lily.garden/lily/Gozen)」「[今村咲魅](https://lemonade.lily.garden/lily/Imamura_Sakumi)」「[六角瀬名](https://lemonade.lily.garden/lily/Rokkaku_Sena)」で矛盾のない文章に出来れば良いと思います。

**Comment by miyacorata** [comment]
8ff86410029ae0195998351ba4b07d64e7d33869 で修正が完了しました。次回のリリースで適用されます。ご指摘ありがとうございました！
