### ISSUE TITLE
名前が長い人をスマホで見ると隙間がなくなる

### ISSUE THREAD

**Issue by fvh-P** [miyacorata/Lemonade#201]
名前の読み表示が折り返されても隙間が広がらないのが原因？

端末: iPhone12 Pro
ブラウザ: iOS Chrome

![1858B1D9-26F4-4836-AB98-D0E21D16C58E](https://user-images.githubusercontent.com/8458066/149505794-6ea62eb1-c862-45be-bf4e-8947dc9a831a.jpeg)

**Comment by miyacorata** [comment]
98e72d0646ff317248adb9b79d8c253f14d14ace でとりあえず修正しました

人名長さの閾値を変更し日葵様も対象にしました。抜本解決ではないのでもうすこし片隅で考えます。
